version: "3.9"

services:
  web:
    build: .
    container_name: sqa_api_app
    ports:
      - "5000:5000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SECRET_KEY=${SECRET_KEY}
    env_file:
      - .env